# Generated by Django 5.1.6 on 2025-08-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='game_gamese_score_9ff815_idx',
            old_name='game_gamesession_score_ended_idx',
        ),
        migrations.RenameIndex(
            model_name='gamesession',
            new_name='game_gamese_ended_a_ce75d9_idx',
            old_name='game_gamesession_ended_at_idx',
        ),
        migrations.RenameIndex(
            model_name='player',
            new_name='game_player_name_13b648_idx',
            old_name='game_player_name_idx',
        ),
    ]
